### PR TITLE
File Entry Padding Correction

### LINKED ISSUE #2: Incorrect Padding When Content Fills a Block Exactly
When the size of an input file is exactly a factor of `512` (the block size), then an extra block of null bytes is incorrectly appended to the file content, causing the resulting tar archive to be corrupt.

Source Reference:
https://github.com/conjurinc/memtar/blob/17adecc1d048d9e7fffed7c6af22139a5300b1d3/lib/memtar.rb#L19

### PR DESCRIPTION
**Pull request by micahlee**
Closes #2 

This PR updates the file entry padding calculation to account for files that are exact factors of 512 bytes. The current calculation, `512 - (size % 512)`, adds an entire 512 block of null bytes for this case, resulting in an invalid tar archive.

It accomplishes this by adding a final modulus operation (`% 512`) to ensure an even division results in a `0` result.

### CODE REVIEW

File: lib/memtar.rb [hunk 1]
```diff
@@ -16,7 +16,7 @@ def add_file path, content, opts = {}
     size = content.bytesize
     @io.write header opts.merge size: size, name: path
     @io.write content
-    @io.write "\0" * (512 - size % 512)
+    @io.write "\0" * ((512 - size % 512) % 512)
```
Comment (jonahx) [inline lib/memtar.rb:19]: Wouldn't  `"\0" * (size % 512)` accomplish the same thing?

Comment (micahlee) [reply lib/memtar.rb:19]: Close, but not quite:

| Size | Current <br/> (`512 - size % 512`) | Change <br /> (`(512 - size % 512) % 512`) | Suggested <br /> (`size % 512`) |
| ---- | ---------------------------- | ----------------------------------- | ------------------------ |
| 0    | 512                          | 0                                   | 0                        |
| 100 | 412 | 412 | 100 |
| 256 | 256 | 256 | 256 |
| 400 | 112 | 112 | 400 |
| 512 | 512 | 0 | 0 |

**Review by jonahx — APPROVED** [review]

File: lib/memtar.rb (hunk 1 above)
Comment (jonahx) [reply lib/memtar.rb:19]: Ah my bad, read too quick.
